org: camxus
app: quickpark
service: apollo-lambda

provider:
  name: aws
  stage: ${opt:stage, 'prod'}
  runtime: nodejs18.x
  httpApi:
    cors: true
  region: eu-west-1  # Default to 'us-east-1' if not set
  environment:
    AWS_REGION_CODE: ${env:AWS_REGION_CODE, 'eu-west-1'}  # Default to 'us-east-1' if not set


functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - httpApi:
        path: /graphql
        method: POST
    - httpApi:
        path: /graphql
        method: GET
plugins:
  - serverless-plugin-typescript
  - aws-amplify-serverless-plugin
  - serverless-dotenv-plugin

custom:
  amplify:
    - filename: src/aws-exports.js
      type: javascript
