org: camxus
app: apollo-lambda
service: apollo-lambda

provider:
  name: aws
  stage: ${opt:stage, 'dev'}
  runtime: nodejs18.x
  httpApi:
    cors: true

functions:
  graphql:
    # this is formatted as <FILENAME>.<HANDLER>
    handler: graphql.graphqlHandler
    events:
    - httpApi:
        path: /graphql
        method: POST
    - httpApi:
        path: /graphql
        method: GET
plugins:
  - serverless-plugin-typescript
  - aws-amplify-serverless-plugin

custom:
  amplify:
    - filename: src/aws-exports.js
      type: javascript
